site_name: Sewer's Front Page
site_url: https://sewer56.dev

plugins:
  - blog
  - offline
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - exclude-unused-files:
      file_types_to_check: [ "psd", "7z", "kra" ]
      file_types_override_mode: append
      enabled: true
  - exclude:
      # Exclude the Theme's own files.
      glob:
        - Reloaded/Pages/*
        - Reloaded/docs/*
        - Reloaded/Readme.md
        - Reloaded/LICENSE
        - Reloaded/mkdocs.yml

extra_css:
  - Reloaded/Stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.snippets
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - content.tooltips
    - navigation.instant
  custom_dir: overrides

nav:
  - Home: index.md  
  - Software, Tools & Libraries: index-libraries.md
  - Games: 
    - Index: index-games.md
    - Common/General: games/common.md
    - Bloons TD 6: games/btd6.md
    - Flatout 2: games/flatout-2.md
    - Persona 3/4/5 PC: games/persona-pc.md
    - Shadow The Hedgehog: games/shadow-the-hedgehog.md
    - Sonic Heroes: games/sonic-heroes.md
    - Sonic Riders: games/sonic-riders.md
    - Sonic 3 A.I.R.: games/sonic-3-air.md
    - Tokyo Xanadu eX+: games/tokyo-xanadu.md
    - Trails of Cold Steel: games/cold-steel.md
    - Trails in The Sky: games/trails-in-the-sky.md
  - Blog:
    - blog/index.md
    